FROM golang:1.20.8-alpine AS builder
RUN apk --no-cache add bash git make gcc g++
RUN git clone https://github.com/edenhill/librdkafka.git \
    && cd librdkafka \
    && ./configure \
    && make \
    && make install
WORKDIR /app
COPY . /app
ENV SERVER_DIR=./server/main.go
ENV SERVER_BIN_DIR=./build/app

RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -o ${SERVER_BIN_DIR} ./${SERVER_DIR}
# Final stage
FROM golang:1.20.8-alpine
RUN apk --no-cache add bash
WORKDIR /
COPY --from=builder /app/build .
ENV PORT=8080
ENTRYPOINT [ "/app" ]